"""Regenerate zeek_tables.py (the name tables the Zeek-style analyzer uses) from a Zeek checkout.

    python tools/gen_zeek_tables.py /path/to/zeek > zeek_tables.py

Only the constant tables are taken (cipher-suite names, TLS versions, curves, alerts,
DNS query types, classes, rcodes, opcodes, DHCP message types), so that LinkTest's logs
use exactly the same spellings as Zeek. Zeek is BSD-licensed; the header of the
generated file carries its copyright notice.
"""
from __future__ import annotations

import os
import re
import sys

TABLES = [
    ("scripts/base/protocols/ssl/consts.zeek", "version_strings", "SSL_VERSIONS"),
    ("scripts/base/protocols/ssl/consts.zeek", "alert_descriptions", "SSL_ALERTS"),
    ("scripts/base/protocols/ssl/consts.zeek", "extensions", "SSL_EXTENSIONS"),
    ("scripts/base/protocols/ssl/consts.zeek", "ec_curves", "SSL_CURVES"),
    ("scripts/base/protocols/ssl/consts.zeek", "cipher_desc", "SSL_CIPHERS"),
    ("scripts/base/protocols/dns/consts.zeek", "query_types", "DNS_QTYPES"),
    ("scripts/base/protocols/dns/consts.zeek", "base_errors", "DNS_RCODES"),
    ("scripts/base/protocols/dns/consts.zeek", "classes", "DNS_CLASSES"),
    ("scripts/base/protocols/dns/consts.zeek", "opcodes", "DNS_OPCODES"),
    ("scripts/base/protocols/dhcp/consts.zeek", "message_types", "DHCP_MSG_TYPES"),
]


def symbols(text: str) -> dict:
    out = {}
    for m in re.finditer(r"const\s+([A-Za-z0-9_]+)\s*=\s*(0x[0-9A-Fa-f]+|\d+)\s*;", text):
        out[m.group(1)] = int(m.group(2), 0)
    return out


def table(text: str, name: str, syms: dict) -> dict:
    m = re.search(r"const\s+" + name + r"\b[^=]*=\s*\{(.*?)\n\s*\}", text, re.S)
    if not m:
        raise SystemExit(f"table {name} not found")
    out = {}
    for e in re.finditer(r"\[\s*([A-Za-z0-9_]+)\s*\]\s*=\s*\"([^\"]*)\"", m.group(1)):
        k = e.group(1)
        key = int(k, 0) if re.fullmatch(r"0x[0-9A-Fa-f]+|\d+", k) else syms.get(k)
        if key is not None:
            out[key] = e.group(2)
    return out


def main() -> int:
    root = sys.argv[1] if len(sys.argv) > 1 else "."
    print('"""Name tables for the Zeek-style analyzer, generated by tools/gen_zeek_tables.py from Zeek\'s scripts.')
    print()
    print("Copyright (c) 1995-now, The Regents of the University of California through the Lawrence")
    print("Berkeley National Laboratory and the International Computer Science Institute. All rights reserved.")
    print("Redistribution and use in source and binary forms, with or without modification, are permitted")
    print("under the BSD 3-clause terms in Zeek's COPYING file. THIS DATA IS PROVIDED \"AS IS\" WITHOUT WARRANTY.")
    print('"""')
    print("# fmt: off")
    cache: dict[str, str] = {}
    for path, name, py in TABLES:
        if path not in cache:
            with open(os.path.join(root, path), encoding="utf-8") as f:
                cache[path] = f.read()
        text = cache[path]
        t = table(text, name, symbols(text))
        print(f"{py} = {{")
        for k in sorted(t):
            print(f"    {k}: {t[k]!r},")
        print("}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
